/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC3475,
  IERC3475Interface,
} from "../../../contracts/Frappucino.sol/IERC3475";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "classId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC3475__factory {
  static readonly abi = _abi;
  static createInterface(): IERC3475Interface {
    return new Interface(_abi) as IERC3475Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC3475 {
    return new Contract(address, _abi, runner) as unknown as IERC3475;
  }
}
