/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Frappucino__factory } from "./Frappucino__factory";
export { IERC3475__factory } from "./IERC3475__factory";
